name: admin_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  fl_chart: ^0.68.0
  csv: ^6.0.0
  file_picker: ^8.0.0
  intl: ^0.19.0
  google_fonts: ^4.0.4
  animate_do: ^3.1.2
  uuid: ^4.5.0
  excel: ^4.0.6
  file_saver: ^0.2.14
  rxdart: ^0.27.1
  mime: ^1.0.0
  permission_handler: ^11.3.0
  open_file: ^3.3.2
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.2.2
  lottie: ^3.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/splash.json
    - assets/animations/menu.json
    - assets/planets/planet1.png
    - assets/planets/planet2.png
    - assets/planets/planet3.png
    - assets/images/profile.jpg
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700